# Generated by Django 4.1.5 on 2023-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_alter_departments_options_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='current_token',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctors',
            name='next_token',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctors',
            name='tokens',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
