# Generated by Django 4.1.5 on 2023-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_doctors_current_token_doctors_next_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='tokens',
            field=models.TextField(blank=True),
        ),
    ]
